import { config as loadEnv } from "dotenv";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import type { Condition, ListingStatus } from "../src/generated/prisma/enums";

loadEnv({ path: ".env.local" });
loadEnv();

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL! });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const items: Array<{
  title: string; slug: string; manufacturer: string; category: string;
  model?: string | null; quantity: number; description: string;
  condition: Condition; status: ListingStatus; callForPrice: boolean;
}> = [
  {
    "title": "AMP Pistol Grip System Multiplexer Hand Tool Kit",
    "slug": "amp-pistol-grip-system-multiplexer-hand-tool-kit",
    "manufacturer": "AMP",
    "category": "Hand Tools",
    "model": "0-0658164",
    "quantity": 1,
    "description": "Pistol Grip System Multiplexer Hand Tool Kit Part/model number: 0-0658164. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Mini Arbor Frame Assembly",
    "slug": "amp-mini-arbor-frame-assembly",
    "manufacturer": "AMP",
    "category": "Presses",
    "model": "P/N 91295-1",
    "quantity": 2,
    "description": "Mini Arbor Frame Assembly Part/model number: P/N 91295-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Manual Arbor Presses",
    "slug": "amp-manual-arbor-presses",
    "manufacturer": "AMP",
    "category": "Presses",
    "model": "P/N 91085-2",
    "quantity": 4,
    "description": "Manual Arbor Presses Part/model number: P/N 91085-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Crimp Tool",
    "slug": "amp-crimp-tool",
    "manufacturer": "AMP",
    "category": "Crimp Tools",
    "model": "P/N 220061-1",
    "quantity": 1,
    "description": "Crimp Tool Part/model number: P/N 220061-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator Guards",
    "slug": "amp-applicator-guards",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "P/N 462987-1-C (4);              P/N 457133-1-F (1)",
    "quantity": 5,
    "description": "Applicator Guards Part/model number: P/N 462987-1-C (4);              P/N 457133-1-F (1). One of the 4 is bent a little, cracked lexan. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "ASG Preset Manual Screwdriver",
    "slug": "asg-preset-manual-screwdriver",
    "manufacturer": "ASG",
    "category": "Screwdrivers",
    "model": "P15",
    "quantity": 1,
    "description": "Preset Manual Screwdriver Part/model number: P15. SKY #65106. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Associated Research Ground Bond Tester",
    "slug": "associated-research-ground-bond-tester",
    "manufacturer": "Associated Research",
    "category": "Test Equipment",
    "model": "HYAMP JR 3030D",
    "quantity": 1,
    "description": "Ground Bond Tester Part/model number: HYAMP JR 3030D. #A140245. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Astro Tool Corp Crimp Tool",
    "slug": "astro-tool-corp-crimp-tool",
    "manufacturer": "Astro Tool Corp",
    "category": "Crimp Tools",
    "model": "10623",
    "quantity": 1,
    "description": "Crimp Tool Part/model number: 10623. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Bendix Inserters",
    "slug": "bendix-inserters",
    "manufacturer": "Bendix",
    "category": "Inserters",
    "model": null,
    "quantity": 2,
    "description": "Inserters Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "BK Precision DC Power Supply",
    "slug": "bk-precision-dc-power-supply",
    "manufacturer": "BK Precision",
    "category": "Power Supplies",
    "model": "1670",
    "quantity": 1,
    "description": "DC Power Supply Part/model number: 1670. #281-3170. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "BK Precision DC Power Supply",
    "slug": "bk-precision-dc-power-supply-2",
    "manufacturer": "BK Precision",
    "category": "Power Supplies",
    "model": null,
    "quantity": 1,
    "description": "DC Power Supply #0024. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Cirris Capacitance Detection Probes",
    "slug": "cirris-capacitance-detection-probes",
    "manufacturer": "Cirris",
    "category": "Test Equipment",
    "model": "CP-1",
    "quantity": 2,
    "description": "Capacitance Detection Probes Part/model number: CP-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Cirris Tester w/Add-Ons",
    "slug": "cirris-tester-wadd-ons",
    "manufacturer": "Cirris",
    "category": "Test Equipment",
    "model": "1000R+",
    "quantity": 1,
    "description": "Tester w/Add-Ons Part/model number: 1000R+. #10590. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Cirris Tester w/Add-Ons",
    "slug": "cirris-tester-wadd-ons-2",
    "manufacturer": "Cirris",
    "category": "Test Equipment",
    "model": "Signature 2000",
    "quantity": 1,
    "description": "Tester w/Add-Ons Part/model number: Signature 2000. #21343. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Cirris Box of assorted Test Adapters",
    "slug": "cirris-box-of-assorted-test-adapters",
    "manufacturer": "Cirris",
    "category": "Test Equipment",
    "model": null,
    "quantity": 1,
    "description": "Box of assorted Test Adapters Sold as a lot. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Daniels (DMC) Gage GO .0390 - NO-GO .0440",
    "slug": "daniels-dmc-gage-go-0390-no-go-0440",
    "manufacturer": "Daniels (DMC)",
    "category": "Measuring Equipment",
    "model": "G125",
    "quantity": 3,
    "description": "Gage GO .0390 - NO-GO .0440 Part/model number: G125. P/N M22520/3-1;  https://dmctools.com/g125. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Daniels (DMC) Open Frame Crimp Tool for use with Interchangeable Y Dies",
    "slug": "daniels-dmc-open-frame-crimp-tool-for-use-with-interchangeable-y-dies",
    "manufacturer": "Daniels (DMC)",
    "category": "Crimp Tools",
    "model": "HX4",
    "quantity": 2,
    "description": "Open Frame Crimp Tool for use with Interchangeable Y Dies Part/model number: HX4. P/N M22520/5-01. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Daniels (DMC) Crimp Tool for Pin and Socket Contacts 8-16AWG",
    "slug": "daniels-dmc-crimp-tool-for-pin-and-socket-contacts-8-16awg",
    "manufacturer": "Daniels (DMC)",
    "category": "Crimp Tools",
    "model": "M310",
    "quantity": 1,
    "description": "Crimp Tool for Pin and Socket Contacts 8-16AWG Part/model number: M310. w/Locator;  NEW. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "NEW",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Daniels (DMC) Inserters",
    "slug": "daniels-dmc-inserters",
    "manufacturer": "Daniels (DMC)",
    "category": "Inserters",
    "model": "TP585, TP731, Cage 11851",
    "quantity": 2,
    "description": "Inserters Part/model number: TP585, TP731, Cage 11851. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Daniels (DMC) Pneumatic Indent Crimp Tools",
    "slug": "daniels-dmc-pneumatic-indent-crimp-tools",
    "manufacturer": "Daniels (DMC)",
    "category": "Crimp Tools",
    "model": "WA27F",
    "quantity": 2,
    "description": "Pneumatic Indent Crimp Tools Part/model number: WA27F. Equivalent to AF8, 12-26AWG. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Despatch Oven (120v/1ph/60hz/1200W",
    "slug": "despatch-oven-120v1ph60hz1200w",
    "manufacturer": "Despatch",
    "category": "Ovens",
    "model": "LDB1-24",
    "quantity": 1,
    "description": "Oven (120v/1ph/60hz/1200W Part/model number: LDB1-24. #133091, Max Temp 204C/400F, 24\" W x 12\" H x 14\" D Chamber. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Eraser Cable Stripper",
    "slug": "eraser-cable-stripper",
    "manufacturer": "Eraser",
    "category": "Wire Processing",
    "model": "LS10",
    "quantity": 1,
    "description": "Cable Stripper Part/model number: LS10. AR #0240. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Extech H.D. Differential Pressure Manometer Low Range (0-5psi)",
    "slug": "extech-hd-differential-pressure-manometer-low-range-0-5psi",
    "manufacturer": "Extech",
    "category": "Measuring Equipment",
    "model": "HD750",
    "quantity": 1,
    "description": "H.D. Differential Pressure Manometer Low Range (0-5psi) Part/model number: HD750. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Foerster Magnetoscop 1.069",
    "slug": "foerster-magnetoscop-1069",
    "manufacturer": "Foerster",
    "category": "Measuring Equipment",
    "model": "9063870",
    "quantity": 1,
    "description": "Magnetoscop 1.069 Part/model number: 9063870. THESE 2 GO WITH EACH OTHER. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Foerster Magnetoscop Probe/Sensor",
    "slug": "foerster-magnetoscop-probesensor",
    "manufacturer": "Foerster",
    "category": "Measuring Equipment",
    "model": "9081135",
    "quantity": 1,
    "description": "Magnetoscop Probe/Sensor Part/model number: 9081135. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Glenair Hand Wrenches",
    "slug": "glenair-hand-wrenches",
    "manufacturer": "Glenair",
    "category": "Hand Tools",
    "model": null,
    "quantity": 3,
    "description": "Hand Wrenches Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "GQ Electronics Hot Air/Soldering SMD Network Station",
    "slug": "gq-electronics-hot-airsoldering-smd-network-station",
    "manufacturer": "GQ Electronics",
    "category": "Solder Stations",
    "model": "5200",
    "quantity": 1,
    "description": "Hot Air/Soldering SMD Network Station Part/model number: 5200. ** Does not work **. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Greenlee Hydraulic Knockout Driver Set",
    "slug": "greenlee-hydraulic-knockout-driver-set",
    "manufacturer": "Greenlee",
    "category": "Hand Tools",
    "model": "1731H767",
    "quantity": 1,
    "description": "Hydraulic Knockout Driver Set Part/model number: 1731H767. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hipotronics Hipot & Megohmeter",
    "slug": "hipotronics-hipot-megohmeter",
    "manufacturer": "Hipotronics",
    "category": "Test Equipment",
    "model": "H300B",
    "quantity": 1,
    "description": "Hipot & Megohmeter Part/model number: H300B. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hirose Hand Crimper",
    "slug": "hirose-hand-crimper",
    "manufacturer": "Hirose",
    "category": "Crimp Tools",
    "model": "DF11-TA22HC",
    "quantity": 1,
    "description": "Hand Crimper Part/model number: DF11-TA22HC. for Terminals DF-22SCA. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hirose Hand Crimper",
    "slug": "hirose-hand-crimper-2",
    "manufacturer": "Hirose",
    "category": "Crimp Tools",
    "model": "HIF3-TB2226HC",
    "quantity": 1,
    "description": "Hand Crimper Part/model number: HIF3-TB2226HC. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Lapp Hand Tool",
    "slug": "lapp-hand-tool",
    "manufacturer": "Lapp",
    "category": "Hand Tools",
    "model": null,
    "quantity": 1,
    "description": "Hand Tool P/N 11147000. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Litton Inserters",
    "slug": "litton-inserters",
    "manufacturer": "Litton",
    "category": "Inserters",
    "model": null,
    "quantity": 5,
    "description": "Inserters Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Lumberg IDC Crimper",
    "slug": "lumberg-idc-crimper",
    "manufacturer": "Lumberg",
    "category": "Crimp Tools",
    "model": "HZ30",
    "quantity": 1,
    "description": "IDC Crimper Part/model number: HZ30. #1710/2010. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Marath Inserters",
    "slug": "marath-inserters",
    "manufacturer": "Marath",
    "category": "Inserters",
    "model": null,
    "quantity": 2,
    "description": "Inserters Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Milford Riveter",
    "slug": "milford-riveter",
    "manufacturer": "Milford",
    "category": "Hand Tools",
    "model": "S-63",
    "quantity": 1,
    "description": "Riveter Part/model number: S-63. #1758;   Tooled for Rivet 508. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Mitutoyo Digimatic Caliper",
    "slug": "mitutoyo-digimatic-caliper",
    "manufacturer": "Mitutoyo",
    "category": "Measuring Equipment",
    "model": "CD-6\" C",
    "quantity": 1,
    "description": "Digimatic Caliper Part/model number: CD-6\" C. #0097548,  Code 500-171. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Mitutoyo Caliper",
    "slug": "mitutoyo-caliper",
    "manufacturer": "Mitutoyo",
    "category": "Measuring Equipment",
    "model": null,
    "quantity": 1,
    "description": "Caliper #505-626-50. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex (assorted) Hand Crimpers",
    "slug": "molex-assorted-hand-crimpers",
    "manufacturer": "Molex (assorted)",
    "category": "Crimp Tools",
    "model": "Assorted",
    "quantity": 1,
    "description": "Hand Crimpers Part/model number: Assorted. Sold as a lot. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Hand Crimper",
    "slug": "molex-hand-crimper",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "HTR1031E",
    "quantity": 1,
    "description": "Hand Crimper Part/model number: HTR1031E. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Hand Crimper",
    "slug": "molex-hand-crimper-2",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": null,
    "quantity": 1,
    "description": "Hand Crimper P/N 63811-8700. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Nitronic Coax Stripper",
    "slug": "nitronic-coax-stripper",
    "manufacturer": "Nitronic",
    "category": "Wire Processing",
    "model": "ST730T",
    "quantity": 1,
    "description": "Coax Stripper Part/model number: ST730T. #1806025;  2019, Cycle Count: 12,392; Micro-Coax Mode. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Norgren Pneumatic Filter Regulator",
    "slug": "norgren-pneumatic-filter-regulator",
    "manufacturer": "Norgren",
    "category": "Pneumatic Tools",
    "model": "B73G-4AK-AD1-RMG",
    "quantity": 1,
    "description": "Pneumatic Filter Regulator Part/model number: B73G-4AK-AD1-RMG. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit Micro Crimp Tool",
    "slug": "panduit-micro-crimp-tool",
    "manufacturer": "Panduit",
    "category": "Crimp Tools",
    "model": "BlackFin CT-2300",
    "quantity": 1,
    "description": "Micro Crimp Tool Part/model number: BlackFin CT-2300. #268531;  rated 26-10 AWG; Battery Operated. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Pasternack Hand Crimpers for PE5010-2",
    "slug": "pasternack-hand-crimpers-for-pe5010-2",
    "manufacturer": "Pasternack",
    "category": "Crimp Tools",
    "model": "PE5009",
    "quantity": 3,
    "description": "Hand Crimpers for PE5010-2 Part/model number: PE5009. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Pasternack Crimp Die",
    "slug": "pasternack-crimp-die",
    "manufacturer": "Pasternack",
    "category": "Crimp Tools",
    "model": "PE5010-2",
    "quantity": 1,
    "description": "Crimp Die Part/model number: PE5010-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Schleuniger Prefeed",
    "slug": "schleuniger-prefeed",
    "manufacturer": "Schleuniger",
    "category": "Wire Processing",
    "model": "PF1000",
    "quantity": 1,
    "description": "Prefeed Part/model number: PF1000. #899-1999               (Missing Reel Shaft & Tension Arm). Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Schleuniger Automatic Cutter",
    "slug": "schleuniger-automatic-cutter",
    "manufacturer": "Schleuniger",
    "category": "Wire Processing",
    "model": "OC3950",
    "quantity": 1,
    "description": "Automatic Cutter Part/model number: OC3950. #1301-1999. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Schleuniger OmniStrip w/Tooling, Manual",
    "slug": "schleuniger-omnistrip-wtooling-manual",
    "manufacturer": "Schleuniger",
    "category": "Wire Processing",
    "model": "OS9400",
    "quantity": 1,
    "description": "OmniStrip w/Tooling, Manual Part/model number: OS9400. #270-1999; Guide & Exit Tubes, 2,4,6,8,10, 12; 2 sets V Blades; set of 5.5mm Radius Blade;  4mm T Wrench; Shuttle Blas\u00e9 Assembly. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Schleuniger Wire Stripper",
    "slug": "schleuniger-wire-stripper",
    "manufacturer": "Schleuniger",
    "category": "Wire Processing",
    "model": "US2500",
    "quantity": 1,
    "description": "Wire Stripper Part/model number: US2500. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Simco Volumn Static Eliminator",
    "slug": "simco-volumn-static-eliminator",
    "manufacturer": "Simco",
    "category": "Static Control",
    "model": "VSE 3000",
    "quantity": 1,
    "description": "Volumn Static Eliminator Part/model number: VSE 3000. P/N 10735-001,  #124910735014939. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sumitomo Optical Fiber Fusion Splicer",
    "slug": "sumitomo-optical-fiber-fusion-splicer",
    "manufacturer": "Sumitomo",
    "category": "Fiber Optic Equipment",
    "model": "Q102-CA",
    "quantity": 1,
    "description": "Optical Fiber Fusion Splicer Part/model number: Q102-CA. #734931697003, 04/2017. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sumitomo Optical Fiber Fusion Splicer",
    "slug": "sumitomo-optical-fiber-fusion-splicer-2",
    "manufacturer": "Sumitomo",
    "category": "Fiber Optic Equipment",
    "model": "QH201e-VS",
    "quantity": 1,
    "description": "Optical Fiber Fusion Splicer Part/model number: QH201e-VS. #064930747019, 05/2016. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "3M Scotchflex Flat Cable Presses",
    "slug": "3m-scotchflex-flat-cable-presses",
    "manufacturer": "3M Scotchflex",
    "category": "Presses",
    "model": "3335",
    "quantity": 2,
    "description": "Flat Cable Presses Part/model number: 3335. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE Hand Crimper",
    "slug": "te-hand-crimper",
    "manufacturer": "TE",
    "category": "Crimp Tools",
    "model": null,
    "quantity": 1,
    "description": "Hand Crimper P/N 55893-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weller Solder Stations",
    "slug": "weller-solder-stations",
    "manufacturer": "Weller",
    "category": "Solder Stations",
    "model": "WE1010",
    "quantity": 3,
    "description": "Solder Stations Part/model number: WE1010. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weller Solder Stations, Digital",
    "slug": "weller-solder-stations-digital",
    "manufacturer": "Weller",
    "category": "Solder Stations",
    "model": "WD1",
    "quantity": 3,
    "description": "Solder Stations, Digital Part/model number: WD1. Serie: 092 15/15 2717. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weller Solder Station",
    "slug": "weller-solder-station",
    "manufacturer": "Weller",
    "category": "Solder Stations",
    "model": "WT1",
    "quantity": 1,
    "description": "Solder Station Part/model number: WT1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Winchester Inserters",
    "slug": "winchester-inserters",
    "manufacturer": "Winchester",
    "category": "Inserters",
    "model": null,
    "quantity": 2,
    "description": "Inserters Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Inserters",
    "slug": "inserters",
    "manufacturer": "Unknown",
    "category": "Inserters",
    "model": null,
    "quantity": 6,
    "description": "Inserters Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Insulation Displacement Crimper (IDC)",
    "slug": "insulation-displacement-crimper-idc",
    "manufacturer": "Unknown",
    "category": "Crimp Tools",
    "model": null,
    "quantity": 1,
    "description": "Insulation Displacement Crimper (IDC) w/Foot Pedal. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sets of Standard Die Envelope Dies",
    "slug": "sets-of-standard-die-envelope-dies",
    "manufacturer": "Unknown",
    "category": "Tooling & Dies",
    "model": null,
    "quantity": 1,
    "description": "Sets of Standard Die Envelope Dies Sold as a lot. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Turret Locators for mil spec pins to crimp in a DMC type connector /press",
    "slug": "turret-locators-for-mil-spec-pins-to-crimp-in-a-dmc-type-connector-press",
    "manufacturer": "Unknown",
    "category": "Presses",
    "model": null,
    "quantity": 9,
    "description": "Turret Locators for mil spec pins to crimp in a DMC type connector /press Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Mate-N-Lock Connector, Split Pin AU-BR",
    "slug": "amp-mate-n-lock-connector-split-pin-au-br",
    "manufacturer": "AMP",
    "category": "Connectors & Terminals",
    "model": "350699-2",
    "quantity": 1,
    "description": "Mate-N-Lock Connector, Split Pin AU-BR Part/model number: 350699-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP ULTRA-FAST 187 ASY REC 22-18 TPBR",
    "slug": "amp-ultra-fast-187-asy-rec-22-18-tpbr",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "2-520401-2",
    "quantity": 1,
    "description": "ULTRA-FAST 187 ASY REC 22-18 TPBR Part/model number: 2-520401-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Plating",
    "slug": "plating",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Plating Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP CMNL SOK 20-14 TP BR",
    "slug": "amp-cmnl-sok-20-14-tp-br",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "61117-1",
    "quantity": 1,
    "description": "CMNL SOK 20-14 TP BR Part/model number: 61117-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP MNL PIN 20-14 TPBR",
    "slug": "amp-mnl-pin-20-14-tpbr",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "61118-1",
    "quantity": 1,
    "description": "MNL PIN 20-14 TPBR Part/model number: 61118-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP MINI UMNL SOK 22-18 AWG SN",
    "slug": "amp-mini-umnl-sok-22-18-awg-sn",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "770904-1",
    "quantity": 1,
    "description": "MINI UMNL SOK 22-18 AWG SN Part/model number: 770904-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex KK254 Crimp Terminal, Female,",
    "slug": "molex-kk254-crimp-terminal-female",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "P/N 0008550101",
    "quantity": 1,
    "description": "KK254 Crimp Terminal, Female, Part/model number: P/N 0008550101. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "30-22AWG, 0.38um Selectrive Gold (Au)",
    "slug": "30-22awg-038um-selectrive-gold-au",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "30-22AWG, 0.38um Selectrive Gold (Au) Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Mating Plating, Nickel Termination",
    "slug": "mating-plating-nickel-termination",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Mating Plating, Nickel Termination Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Plating, Brass",
    "slug": "plating-brass",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Plating, Brass Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 2.36mm Dia, Standard .093\" Pin and",
    "slug": "molex-236mm-dia-standard-093-pin-and",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "P/N 02-09-2101",
    "quantity": 1,
    "description": "2.36mm Dia, Standard .093\" Pin and Part/model number: P/N 02-09-2101. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Socket Crimp Terminal, Series 1190,",
    "slug": "socket-crimp-terminal-series-1190",
    "manufacturer": "Unknown",
    "category": "Crimp Tools",
    "model": null,
    "quantity": 1,
    "description": "Socket Crimp Terminal, Series 1190, Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Male, w/Tin (Sn) Plated Brass",
    "slug": "male-wtin-sn-plated-brass",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "Male, w/Tin (Sn) Plated Brass Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Contact, 20-14 AWG",
    "slug": "contact-20-14-awg",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Contact, 20-14 AWG Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex SL Fem Crimp Terminal 22-24 30Gold",
    "slug": "molex-sl-fem-crimp-terminal-22-24-30gold",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "16020088",
    "quantity": 1,
    "description": "SL Fem Crimp Terminal 22-24 30Gold Part/model number: 16020088. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex KK 396 Crimp Terminal 2578, 22-26 AWG,",
    "slug": "molex-kk-396-crimp-terminal-2578-22-26-awg",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "08-50-0133",
    "quantity": 1,
    "description": "KK 396 Crimp Terminal 2578, 22-26 AWG, Part/model number: 08-50-0133. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Phosphor Bronze, Tin (Sn)",
    "slug": "phosphor-bronze-tin-sn",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "Phosphor Bronze, Tin (Sn) Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex KK254 Crimp Terminal, 22-30AWG,",
    "slug": "molex-kk254-crimp-terminal-22-30awg",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "08-55-0101",
    "quantity": 1,
    "description": "KK254 Crimp Terminal, 22-30AWG, Part/model number: 08-55-0101. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Selective Gold (Au), Nickel (Ni) Under",
    "slug": "selective-gold-au-nickel-ni-under",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "Selective Gold (Au), Nickel (Ni) Under Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Micro-Fit 3.0 Crimp Terminal, Female,",
    "slug": "molex-micro-fit-30-crimp-terminal-female",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "43030-0003",
    "quantity": 1,
    "description": "Micro-Fit 3.0 Crimp Terminal, Female, Part/model number: 43030-0003. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "with Select Gold (Au) Plated Phosphor",
    "slug": "with-select-gold-au-plated-phosphor",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "with Select Gold (Au) Plated Phosphor Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Bronze Contact, 24-20 AWG",
    "slug": "bronze-contact-24-20-awg",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Bronze Contact, 24-20 AWG Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Sabre Crimp Terminal, Female,",
    "slug": "molex-sabre-crimp-terminal-female",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "43375-0001",
    "quantity": 1,
    "description": "Sabre Crimp Terminal, Female, Part/model number: 43375-0001. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "14-16 AWG, 3.30mm max. Insulation Dia.,",
    "slug": "14-16-awg-330mm-max-insulation-dia",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "14-16 AWG, 3.30mm max. Insulation Dia., Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Tin (Sn) Plated Brass Contact with TPA",
    "slug": "tin-sn-plated-brass-contact-with-tpa",
    "manufacturer": "Unknown",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "Tin (Sn) Plated Brass Contact with TPA Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Mini-Fit Plus Crimp Terminal, 20-18 AWG,",
    "slug": "molex-mini-fit-plus-crimp-terminal-20-18-awg",
    "manufacturer": "Molex",
    "category": "Crimp Tools",
    "model": "45750-1211",
    "quantity": 1,
    "description": "Mini-Fit Plus Crimp Terminal, 20-18 AWG, Part/model number: 45750-1211. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Copper (Cu) Alloy, Gold (Au) Selective",
    "slug": "copper-cu-alloy-gold-au-selective",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "Copper (Cu) Alloy, Gold (Au) Selective Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "24-30AWG",
    "slug": "24-30awg",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "24-30AWG Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit Quick Connect Terminal, Female,  6.35mm x 0.81mm",
    "slug": "panduit-quick-connect-terminal-female-635mm-x-081mm",
    "manufacturer": "Panduit",
    "category": "Connectors & Terminals",
    "model": "DPF10-250FIB-2K",
    "quantity": 1,
    "description": "Quick Connect Terminal, Female,  6.35mm x 0.81mm Part/model number: DPF10-250FIB-2K. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit 0.187\" (4.75mm), 0.205\" (5.21mm) Quick Connect Female 18-22AWG Crimp Connector, Non-Mating End Insulated",
    "slug": "panduit-0187-475mm-0205-521mm-quick-connect-female-18-22awg-crimp-connector-non-",
    "manufacturer": "Panduit",
    "category": "Connectors & Terminals",
    "model": "DV18-206B-3K",
    "quantity": 1,
    "description": "0.187\" (4.75mm), 0.205\" (5.21mm) Quick Connect Female 18-22AWG Crimp Connector, Non-Mating End Insulated Part/model number: DV18-206B-3K. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit Ring Terminal, nylon insulated, metal sleeve, 16\" 14AWG, #10 stud size",
    "slug": "panduit-ring-terminal-nylon-insulated-metal-sleeve-16-14awg-10-stud-size",
    "manufacturer": "Panduit",
    "category": "Connectors & Terminals",
    "model": "PN14-10R-3K",
    "quantity": 1,
    "description": "Ring Terminal, nylon insulated, metal sleeve, 16\" 14AWG, #10 stud size Part/model number: PN14-10R-3K. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit Ring Terminal Connector, 10 stud circular, 18-22AWG crimp",
    "slug": "panduit-ring-terminal-connector-10-stud-circular-18-22awg-crimp",
    "manufacturer": "Panduit",
    "category": "Connectors & Terminals",
    "model": "PN18-10R-3K",
    "quantity": 1,
    "description": "Ring Terminal Connector, 10 stud circular, 18-22AWG crimp Part/model number: PN18-10R-3K. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE MNL PIN 20-14 TPBR",
    "slug": "te-mnl-pin-20-14-tpbr",
    "manufacturer": "TE",
    "category": "Industrial Equipment",
    "model": "61118-1",
    "quantity": 1,
    "description": "MNL PIN 20-14 TPBR Part/model number: 61118-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE Conn Socket 20-24AWG Gold Crimp",
    "slug": "te-conn-socket-20-24awg-gold-crimp",
    "manufacturer": "TE",
    "category": "Connectors & Terminals",
    "model": "166500-2",
    "quantity": 1,
    "description": "Conn Socket 20-24AWG Gold Crimp Part/model number: 166500-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE UMNL Split Pin AUNI/BR",
    "slug": "te-umnl-split-pin-aunibr",
    "manufacturer": "TE",
    "category": "Industrial Equipment",
    "model": "350687-7",
    "quantity": 1,
    "description": "UMNL Split Pin AUNI/BR Part/model number: 350687-7. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "466320-2-L",
    "quantity": 1,
    "description": "Applicator Part/model number: 466320-2-L. #265325                                                            ** NO Plunger. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator-2",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "466572-3-L",
    "quantity": 1,
    "description": "Applicator Part/model number: 466572-3-L. #524818. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator-3",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "567021-4",
    "quantity": 1,
    "description": "Applicator Part/model number: 567021-4. #370206. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator-4",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "567033-2-D",
    "quantity": 1,
    "description": "Applicator Part/model number: 567033-2-D. #442820. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator-5",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "567200-3-T",
    "quantity": 1,
    "description": "Applicator Part/model number: 567200-3-T. #397575. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Applicator",
    "slug": "amp-applicator-6",
    "manufacturer": "AMP",
    "category": "Applicators",
    "model": "680555-3-C",
    "quantity": 1,
    "description": "Applicator Part/model number: 680555-3-C. #512880. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP/Tyco Applicator",
    "slug": "amptyco-applicator",
    "manufacturer": "AMP/Tyco",
    "category": "Applicators",
    "model": "5673732-G",
    "quantity": 1,
    "description": "Applicator Part/model number: 5673732-G. #448142  (For G Press only). Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP/Tyco/TE Applicator",
    "slug": "amptycote-applicator",
    "manufacturer": "AMP/Tyco/TE",
    "category": "Applicators",
    "model": "567373-2",
    "quantity": 1,
    "description": "Applicator Part/model number: 567373-2. #418142. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "JST Applicator",
    "slug": "jst-applicator",
    "manufacturer": "JST",
    "category": "Applicators",
    "model": "CMKS-L",
    "quantity": 1,
    "description": "Applicator Part/model number: CMKS-L. #3817, w/SIN-002T-1.0 Die Set. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "JST Applicator",
    "slug": "jst-applicator-2",
    "manufacturer": "JST",
    "category": "Applicators",
    "model": "CMKS-L",
    "quantity": 1,
    "description": "Applicator Part/model number: CMKS-L. #2817, w/SPAL-001T-P0.5 Die Set. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "KM USA Applicator",
    "slug": "km-usa-applicator",
    "manufacturer": "KM USA",
    "category": "Applicators",
    "model": "LF-S",
    "quantity": 1,
    "description": "Applicator Part/model number: LF-S. #1122A-10345 (Molex Terminal 43375-0001. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60703C",
    "quantity": 1,
    "description": "Applicator Part/model number: 60703C. #738. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-2",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60706B",
    "quantity": 1,
    "description": "Applicator Part/model number: 60706B. #164. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-3",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60706E",
    "quantity": 1,
    "description": "Applicator Part/model number: 60706E. #107 X. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-4",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60707B",
    "quantity": 1,
    "description": "Applicator Part/model number: 60707B. #152, L.N D95-305. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-5",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60709B",
    "quantity": 1,
    "description": "Applicator Part/model number: 60709B. L.N D95-819. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-6",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60710C",
    "quantity": 1,
    "description": "Applicator Part/model number: 60710C. #187, L.N D95-233. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-7",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60712A",
    "quantity": 1,
    "description": "Applicator Part/model number: 60712A. #478, L.N D94-005. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-8",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "60730B",
    "quantity": 1,
    "description": "Applicator Part/model number: 60730B. #144, L.N 1666. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Applicator",
    "slug": "molex-applicator-9",
    "manufacturer": "Molex",
    "category": "Applicators",
    "model": "63901-8800",
    "quantity": 1,
    "description": "Applicator Part/model number: 63901-8800. #2336. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit Applicator",
    "slug": "panduit-applicator",
    "manufacturer": "Panduit",
    "category": "Applicators",
    "model": "CA-800EZ",
    "quantity": 1,
    "description": "Applicator Part/model number: CA-800EZ. w/CD-800-C2 Crimp Tool, #136027; Extra Crimp Tooling. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE Applicator",
    "slug": "te-applicator",
    "manufacturer": "TE",
    "category": "Applicators",
    "model": "2151263-1-B",
    "quantity": 1,
    "description": "Applicator Part/model number: 2151263-1-B. #1006429, Cycle Count 9956. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "TE Applicator",
    "slug": "te-applicator-2",
    "manufacturer": "TE",
    "category": "Applicators",
    "model": "2266553-1-C",
    "quantity": 1,
    "description": "Applicator Part/model number: 2266553-1-C. #1025969, Cycle Count 152. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 8821",
    "slug": "amp-8821",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90269-2-H",
    "quantity": 1,
    "description": "8821 Part/model number: 90269-2-H. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP B 9321",
    "slug": "amp-b-9321",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90417-1",
    "quantity": 2,
    "description": "B 9321 Part/model number: 90417-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP GRN",
    "slug": "amp-grn",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "GRN Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 9202-03",
    "slug": "amp-9202-03",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "HT-151",
    "quantity": 1,
    "description": "9202-03 Part/model number: HT-151. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 47387",
    "slug": "amp-47387",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "16-14, 21/2-4, P.I.D.G.",
    "quantity": 1,
    "description": "47387 Part/model number: 16-14, 21/2-4, P.I.D.G.. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 59500",
    "slug": "amp-59500",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "59500 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 9852 008",
    "slug": "amp-9852-008",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "58437-1",
    "quantity": 1,
    "description": "9852 008 Part/model number: 58437-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP G 9913 004",
    "slug": "amp-g-9913-004",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90325-1",
    "quantity": 1,
    "description": "G 9913 004 Part/model number: 90325-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP E 9645",
    "slug": "amp-e-9645",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90260-1",
    "quantity": 1,
    "description": "E 9645 Part/model number: 90260-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP BNC, RG-59",
    "slug": "amp-bnc-rg-59",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "220187-2",
    "quantity": 1,
    "description": "BNC, RG-59 Part/model number: 220187-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP BNC, RG-59",
    "slug": "amp-bnc-rg-59-2",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "220187-2-C",
    "quantity": 1,
    "description": "BNC, RG-59 Part/model number: 220187-2-C. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP J 0106 003",
    "slug": "amp-j-0106-003",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90067-5",
    "quantity": 1,
    "description": "J 0106 003 Part/model number: 90067-5. #1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP J 9537",
    "slug": "amp-j-9537",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90067-5",
    "quantity": 1,
    "description": "J 9537 Part/model number: 90067-5. #2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP B 9942 028",
    "slug": "amp-b-9942-028",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90710-2",
    "quantity": 1,
    "description": "B 9942 028 Part/model number: 90710-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP D 9942 003",
    "slug": "amp-d-9942-003",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90418-1",
    "quantity": 1,
    "description": "D 9942 003 Part/model number: 90418-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP 18-10, ECV, ECN",
    "slug": "amp-18-10-ecv-ecn",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "45219-2",
    "quantity": 1,
    "description": "18-10, ECV, ECN Part/model number: 45219-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Certi-Lock",
    "slug": "amp-certi-lock",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "169400 Rev.B  #1",
    "quantity": 1,
    "description": "Certi-Lock Part/model number: 169400 Rev.B  #1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Certi-Lock",
    "slug": "amp-certi-lock-2",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "169400 Rev.B  #2",
    "quantity": 1,
    "description": "Certi-Lock Part/model number: 169400 Rev.B  #2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP Cutter",
    "slug": "amp-cutter",
    "manufacturer": "AMP",
    "category": "Wire Processing",
    "model": "569994-1",
    "quantity": 1,
    "description": "Cutter Part/model number: 569994-1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP H 0048 037",
    "slug": "amp-h-0048-037",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90300-2",
    "quantity": 1,
    "description": "H 0048 037 Part/model number: 90300-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP No Number",
    "slug": "amp-no-number",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "No Number Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP J 9713",
    "slug": "amp-j-9713",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "90066-7",
    "quantity": 1,
    "description": "J 9713 Part/model number: 90066-7. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP D 9550",
    "slug": "amp-d-9550",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "D 9550",
    "quantity": 1,
    "description": "D 9550 Part/model number: D 9550. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP F 0107",
    "slug": "amp-f-0107",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "F 0107",
    "quantity": 1,
    "description": "F 0107 Part/model number: F 0107. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP F 9816",
    "slug": "amp-f-9816",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "F 9816",
    "quantity": 1,
    "description": "F 9816 Part/model number: F 9816. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP G 0247",
    "slug": "amp-g-0247",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "G 0247",
    "quantity": 1,
    "description": "G 0247 Part/model number: G 0247. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "AMP K 9630",
    "slug": "amp-k-9630",
    "manufacturer": "AMP",
    "category": "Industrial Equipment",
    "model": "59287-2",
    "quantity": 1,
    "description": "K 9630 Part/model number: 59287-2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "API Bantam Rota-Crimp",
    "slug": "api-bantam-rota-crimp",
    "manufacturer": "API",
    "category": "Crimp Tools",
    "model": "601280",
    "quantity": 1,
    "description": "Bantam Rota-Crimp Part/model number: 601280. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Berg #33514",
    "slug": "berg-33514",
    "manufacturer": "Berg",
    "category": "Industrial Equipment",
    "model": "HT43",
    "quantity": 1,
    "description": "#33514 Part/model number: HT43. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Berg #27191",
    "slug": "berg-27191",
    "manufacturer": "Berg",
    "category": "Industrial Equipment",
    "model": "HT48",
    "quantity": 1,
    "description": "#27191 Part/model number: HT48. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Buchanan #12144",
    "slug": "buchanan-12144",
    "manufacturer": "Buchanan",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "#12144 #2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Buchanan #612118",
    "slug": "buchanan-612118",
    "manufacturer": "Buchanan",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "#612118 #4. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Buchanan Cat #612118",
    "slug": "buchanan-cat-612118",
    "manufacturer": "Buchanan",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "Cat #612118 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "CDI Torque Screwdriver",
    "slug": "cdi-torque-screwdriver",
    "manufacturer": "CDI",
    "category": "Screwdrivers",
    "model": "61SM",
    "quantity": 1,
    "description": "Torque Screwdriver Part/model number: 61SM. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "DMC Cage 11851",
    "slug": "dmc-cage-11851",
    "manufacturer": "DMC",
    "category": "Industrial Equipment",
    "model": "GMT226",
    "quantity": 1,
    "description": "Cage 11851 Part/model number: GMT226. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "ETC No Number",
    "slug": "etc-no-number",
    "manufacturer": "ETC",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "No Number Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "ETC HC-098",
    "slug": "etc-hc-098",
    "manufacturer": "ETC",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "HC-098 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Fiber Instrument No Numbers",
    "slug": "fiber-instrument-no-numbers",
    "manufacturer": "Fiber Instrument",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 2,
    "description": "No Numbers Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hollingsworth FISO FIIG, SO FIIG",
    "slug": "hollingsworth-fiso-fiig-so-fiig",
    "manufacturer": "Hollingsworth",
    "category": "Industrial Equipment",
    "model": "H-43",
    "quantity": 1,
    "description": "FISO FIIG, SO FIIG Part/model number: H-43. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hollingsworth FIT-FIIG",
    "slug": "hollingsworth-fit-fiig",
    "manufacturer": "Hollingsworth",
    "category": "Industrial Equipment",
    "model": "H-6E",
    "quantity": 1,
    "description": "FIT-FIIG Part/model number: H-6E. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hollingsworth FIT-FIIG",
    "slug": "hollingsworth-fit-fiig-2",
    "manufacturer": "Hollingsworth",
    "category": "Industrial Equipment",
    "model": "H-7A",
    "quantity": 1,
    "description": "FIT-FIIG Part/model number: H-7A. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hollingsworth FISO FLAG",
    "slug": "hollingsworth-fiso-flag",
    "manufacturer": "Hollingsworth",
    "category": "Industrial Equipment",
    "model": "H-46",
    "quantity": 1,
    "description": "FISO FLAG Part/model number: H-46. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hollingsworth FIT-FIIG",
    "slug": "hollingsworth-fit-fiig-3",
    "manufacturer": "Hollingsworth",
    "category": "Industrial Equipment",
    "model": "H-65",
    "quantity": 1,
    "description": "FIT-FIIG Part/model number: H-65. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Hypertronics DMC-USA Cage 11851",
    "slug": "hypertronics-dmc-usa-cage-11851",
    "manufacturer": "Hypertronics",
    "category": "Industrial Equipment",
    "model": "YSK006-011&-009",
    "quantity": 1,
    "description": "DMC-USA Cage 11851 Part/model number: YSK006-011&-009. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "JST 001-0.5",
    "slug": "jst-001-05",
    "manufacturer": "JST",
    "category": "Industrial Equipment",
    "model": "YC670R BBH",
    "quantity": 1,
    "description": "001-0.5 Part/model number: YC670R BBH. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Midland Ross FIT FIIG",
    "slug": "midland-ross-fit-fiig",
    "manufacturer": "Midland Ross",
    "category": "Industrial Equipment",
    "model": "1",
    "quantity": 1,
    "description": "FIT FIIG Part/model number: 1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 11-01-0006",
    "slug": "molex-11-01-0006",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "HTR 2262 #1",
    "quantity": 1,
    "description": "11-01-0006 Part/model number: HTR 2262 #1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex K337082  900039",
    "slug": "molex-k337082-900039",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "K337082  900039 EDP blocked out. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex E099518  995089",
    "slug": "molex-e099518-995089",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "E099518  995089 EDP blocked out. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR5974",
    "slug": "molex-eng-cr5974",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-1094   (#1)",
    "quantity": 1,
    "description": "ENG #CR5974 Part/model number: EDP #11-01-1094   (#1). 127633   994119. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR5974",
    "slug": "molex-eng-cr5974-2",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-1094   (#2)",
    "quantity": 1,
    "description": "ENG #CR5974 Part/model number: EDP #11-01-1094   (#2). 127631  994119. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR60927a",
    "slug": "molex-eng-cr60927a",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-0204",
    "quantity": 1,
    "description": "ENG #CR60927a Part/model number: EDP #11-01-0204. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex P015850  904029",
    "slug": "molex-p015850-904029",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "Order #638113600  #2",
    "quantity": 1,
    "description": "P015850  904029 Part/model number: Order #638113600  #2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex P028960  904039",
    "slug": "molex-p028960-904039",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "Order #638113600  #3",
    "quantity": 1,
    "description": "P028960  904039 Part/model number: Order #638113600  #3. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex P028956  904039",
    "slug": "molex-p028956-904039",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "Order #638113600  #4",
    "quantity": 1,
    "description": "P028956  904039 Part/model number: Order #638113600  #4. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex P028966  904039",
    "slug": "molex-p028966-904039",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "Order #638113600  #5",
    "quantity": 1,
    "description": "P028966  904039 Part/model number: Order #638113600  #5. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex I05 0062",
    "slug": "molex-i05-0062",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "63811-3300",
    "quantity": 1,
    "description": "I05 0062 Part/model number: 63811-3300. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR60622B",
    "slug": "molex-eng-cr60622b",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-0197 #1",
    "quantity": 1,
    "description": "ENG #CR60622B Part/model number: EDP #11-01-0197 #1. K307314  900019. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR606228",
    "slug": "molex-eng-cr606228",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-0197 #2",
    "quantity": 1,
    "description": "ENG #CR606228 Part/model number: EDP #11-01-0197 #2. H038176  998089. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex Mini-Fit SR 14/16",
    "slug": "molex-mini-fit-sr-1416",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "63811-3800",
    "quantity": 1,
    "description": "Mini-Fit SR 14/16 Part/model number: 63811-3800. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex ENG #CR5907",
    "slug": "molex-eng-cr5907",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "EDP #11-01-0189",
    "quantity": 1,
    "description": "ENG #CR5907 Part/model number: EDP #11-01-0189. H020098  998059. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 7160-19, 7160-20",
    "slug": "molex-7160-19-7160-20",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": "No Model",
    "quantity": 1,
    "description": "7160-19, 7160-20 Part/model number: No Model. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 7160-10, 7160-09",
    "slug": "molex-7160-10-7160-09",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "7160-10, 7160-09 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 7160-47, 7160-48     #1",
    "slug": "molex-7160-47-7160-48-1",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "7160-47, 7160-48     #1 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 7160-47, 7160-48     #2",
    "slug": "molex-7160-47-7160-48-2",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "7160-47, 7160-48     #2 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Molex 12-10AWG",
    "slug": "molex-12-10awg",
    "manufacturer": "Molex",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "12-10AWG Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "NTM 444444",
    "slug": "ntm-444444",
    "manufacturer": "NTM",
    "category": "Industrial Equipment",
    "model": "NH-13  #1",
    "quantity": 1,
    "description": "444444 Part/model number: NH-13  #1. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "NTM 8205",
    "slug": "ntm-8205",
    "manufacturer": "NTM",
    "category": "Industrial Equipment",
    "model": "NH-13  #2",
    "quantity": 1,
    "description": "8205 Part/model number: NH-13  #2. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Panduit #32869",
    "slug": "panduit-32869",
    "manufacturer": "Panduit",
    "category": "Industrial Equipment",
    "model": "CTD-156F Nose Assembly",
    "quantity": 1,
    "description": "#32869 Part/model number: CTD-156F Nose Assembly. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sargent 28-24; 24-20",
    "slug": "sargent-28-24-24-20",
    "manufacturer": "Sargent",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "28-24; 24-20 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sargent 22-14; 12-10",
    "slug": "sargent-22-14-12-10",
    "manufacturer": "Sargent",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "22-14; 12-10 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Sargent No Number",
    "slug": "sargent-no-number",
    "manufacturer": "Sargent",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "No Number Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Stakon For T&B Stakon Terminals",
    "slug": "stakon-for-tb-stakon-terminals",
    "manufacturer": "Stakon",
    "category": "Connectors & Terminals",
    "model": null,
    "quantity": 1,
    "description": "For T&B Stakon Terminals Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "T&B No Numbers",
    "slug": "tb-no-numbers",
    "manufacturer": "T&B",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 2,
    "description": "No Numbers Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PZ 16 S",
    "slug": "weidmuller-pz-16-s",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": "901498",
    "quantity": 1,
    "description": "PZ 16 S Part/model number: 901498. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PZ 6/5",
    "slug": "weidmuller-pz-65",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": "901146",
    "quantity": 2,
    "description": "PZ 6/5 Part/model number: 901146. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PZ4",
    "slug": "weidmuller-pz4",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": "901250",
    "quantity": 1,
    "description": "PZ4 Part/model number: 901250. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PZ 3",
    "slug": "weidmuller-pz-3",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": "56730",
    "quantity": 1,
    "description": "PZ 3 Part/model number: 56730. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PZ 3",
    "slug": "weidmuller-pz-3-2",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": "66730",
    "quantity": 1,
    "description": "PZ 3 Part/model number: 66730. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "Weidmuller PA1645",
    "slug": "weidmuller-pa1645",
    "manufacturer": "Weidmuller",
    "category": "Industrial Equipment",
    "model": null,
    "quantity": 1,
    "description": "PA1645 Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  },
  {
    "title": "In Folder",
    "slug": "in-folder",
    "manufacturer": "Unknown",
    "category": "Industrial Equipment",
    "model": "Could Not Identify Mfger",
    "quantity": 40,
    "description": "In Folder Part/model number: Could Not Identify Mfger. Used condition. Available from Tornik equipment liquidation, Rocky Hill, CT.",
    "condition": "USED",
    "status": "ACTIVE",
    "callForPrice": true
  }
]
;

async function main() {
  let created = 0, skipped = 0;
  for (const item of items) {
    const { model, ...rest } = item;
    await prisma.machine.upsert({
      where: { slug: item.slug },
      update: {},
      create: {
        ...rest,
        ...(model ? { model } : {}),
        images: [],
      },
    });
    created++;
  }
  console.log(`Done: ${created} upserted.`);
}

main().catch(console.error).finally(() => pool.end());